// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsqOud44F5xaCt3AAq4sx6eaGeBOxIR1c',
    appId: '1:799081548709:web:9ec53faa08537d6b85764c',
    messagingSenderId: '799081548709',
    projectId: 'chatapp-6bc4f',
    authDomain: 'chatapp-6bc4f.firebaseapp.com',
    storageBucket: 'chatapp-6bc4f.firebasestorage.app',
    measurementId: 'G-MTZRWPT5FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdYppd-Vj8iTNc9zOx95ey-C4MDeEeky0',
    appId: '1:799081548709:android:4d6853b82bfc09e185764c',
    messagingSenderId: '799081548709',
    projectId: 'chatapp-6bc4f',
    storageBucket: 'chatapp-6bc4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgvCeeHA1ZWoWukfKwxTQvPe86DveJjJo',
    appId: '1:799081548709:ios:6cfd1f7a5a934bf785764c',
    messagingSenderId: '799081548709',
    projectId: 'chatapp-6bc4f',
    storageBucket: 'chatapp-6bc4f.firebasestorage.app',
    iosBundleId: 'com.example.assignment9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgvCeeHA1ZWoWukfKwxTQvPe86DveJjJo',
    appId: '1:799081548709:ios:6cfd1f7a5a934bf785764c',
    messagingSenderId: '799081548709',
    projectId: 'chatapp-6bc4f',
    storageBucket: 'chatapp-6bc4f.firebasestorage.app',
    iosBundleId: 'com.example.assignment9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsqOud44F5xaCt3AAq4sx6eaGeBOxIR1c',
    appId: '1:799081548709:web:de72029c939ac13485764c',
    messagingSenderId: '799081548709',
    projectId: 'chatapp-6bc4f',
    authDomain: 'chatapp-6bc4f.firebaseapp.com',
    storageBucket: 'chatapp-6bc4f.firebasestorage.app',
    measurementId: 'G-W0VJKCRNC1',
  );
}
